### ISSUE TITLE
Incompatibility with flake8 v6

### ISSUE THREAD

**Issue by matthiasdiener** [zheller/flake8-quotes#110]
```
$ pip freeze |grep flake
flake8==6.0.0
flake8-quotes==3.3.1
pyflakes==3.0.0

$ flake8
Traceback (most recent call last):
  File "/Users/mdiener/Work/emirge/miniforge3/envs/ceesd/bin/flake8", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/mdiener/Work/emirge/miniforge3/envs/ceesd/lib/python3.11/site-packages/flake8/main/cli.py", line 23, in main
    app.run(argv)
  File "/Users/mdiener/Work/emirge/miniforge3/envs/ceesd/lib/python3.11/site-packages/flake8/main/application.py", line 198, in run
    self._run(argv)
  File "/Users/mdiener/Work/emirge/miniforge3/envs/ceesd/lib/python3.11/site-packages/flake8/main/application.py", line 186, in _run
    self.initialize(argv)
  File "/Users/mdiener/Work/emirge/miniforge3/envs/ceesd/lib/python3.11/site-packages/flake8/main/application.py", line 165, in initialize
    self.plugins, self.options = parse_args(argv)
                                 ^^^^^^^^^^^^^^^^
  File "/Users/mdiener/Work/emirge/miniforge3/envs/ceesd/lib/python3.11/site-packages/flake8/options/parse_args.py", line 51, in parse_args
    option_manager.register_plugins(plugins)
  File "/Users/mdiener/Work/emirge/miniforge3/envs/ceesd/lib/python3.11/site-packages/flake8/options/manager.py", line 259, in register_plugins
    add_options(self)
  File "/Users/mdiener/Work/emirge/miniforge3/envs/ceesd/lib/python3.11/site-packages/flake8_quotes/__init__.py", line 103, in add_options
    cls._register_opt(parser, '--quotes', action='store',
  File "/Users/mdiener/Work/emirge/miniforge3/envs/ceesd/lib/python3.11/site-packages/flake8_quotes/__init__.py", line 93, in _register_opt
    parser.add_option(*args, **kwargs)
  File "/Users/mdiener/Work/emirge/miniforge3/envs/ceesd/lib/python3.11/site-packages/flake8/options/manager.py", line 281, in add_option
    self._current_group.add_argument(*option_args, **option_kwargs)
  File "/Users/mdiener/Work/emirge/miniforge3/envs/ceesd/lib/python3.11/argparse.py", line 1448, in add_argument
    raise ValueError('%r is not callable' % (type_func,))
ValueError: 'choice' is not callable

**Comment by Avasam** [comment]
Small migration guide: https://github.com/PyCQA/flake8/pull/1739
