### ISSUE TITLE
Incompatible with flake8 version 3

### ISSUE THREAD

**Issue by Ichimonji10** [zheller/flake8-quotes#43]
Execute the following, under either Python 2 or 3:

```sh
virtualenv env
source env/bin/activate
pip install --upgrade pip
pip install flake8-quotes
flake8
```

Or, execute the following under Python 3:

```sh
python -m venv env
source env/bin/activate
pip install --upgrade pip
pip install flake8-quotes
flake8
```

Either way, an error like the following will result:

```
(env) [ichimonji10@beech:tmp]$ flake8 .
Traceback (most recent call last):
  File "/home/ichimonji10/tmp/env/lib/python3.5/site-packages/flake8/plugins/manager.py", line 159, in load_plugin
    self._load(verify_requirements)
  File "/home/ichimonji10/tmp/env/lib/python3.5/site-packages/flake8/plugins/manager.py", line 137, in _load
    self._plugin = resolve()
  File "/home/ichimonji10/tmp/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ichimonji10/tmp/env/lib/python3.5/site-packages/flake8_quotes/__init__.py", line 5, in <module>
    from flake8.engine import pep8
ImportError: No module named 'flake8.engine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ichimonji10/tmp/env/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/home/ichimonji10/tmp/env/lib/python3.5/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/home/ichimonji10/tmp/env/lib/python3.5/site-packages/flake8/main/application.py", line 299, in run
    self._run(argv)
  File "/home/ichimonji10/tmp/env/lib/python3.5/site-packages/flake8/main/application.py", line 285, in _run
    self.initialize(argv)
  File "/home/ichimonji10/tmp/env/lib/python3.5/site-packages/flake8/main/application.py", line 275, in initialize
    self.find_plugins()
  File "/home/ichimonji10/tmp/env/lib/python3.5/site-packages/flake8/main/application.py", line 143, in find_plugins
    self.check_plugins.load_plugins()
  File "/home/ichimonji10/tmp/env/lib/python3.5/site-packages/flake8/plugins/manager.py", line 369, in load_plugins
    plugins = list(self.manager.map(load_plugin))
  File "/home/ichimonji10/tmp/env/lib/python3.5/site-packages/flake8/plugins/manager.py", line 261, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/home/ichimonji10/tmp/env/lib/python3.5/site-packages/flake8/plugins/manager.py", line 367, in load_plugin
    return plugin.load_plugin()
  File "/home/ichimonji10/tmp/env/lib/python3.5/site-packages/flake8/plugins/manager.py", line 167, in load_plugin
    raise failed_to_load
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "flake8_quotes" due to No module named 'flake8.engine'.
```

For the record, here's the output of `pip freeze`:

```
flake8==3.0.0
flake8-quotes==0.7.0
mccabe==0.5.0
pycodestyle==2.0.0
pyflakes==1.2.3
```

**Comment by Ichimonji10** [comment]
The following produces a functioning flake8 installation:

```sh
python -m venv env
source env/bin/activate
pip install --upgrade pip
pip install 'flake8<3'
pip install flake8-quotes
```

**Comment by Ichimonji10** [comment]
According to [Writing Plugins for Flake8](http://flake8.pycqa.org/en/latest/plugin-development/index.html), it should be possible to write a plugin that's compatible with flake8 2 and 3:

> All plugins for Flake8 must be registered via entry points. In this section we cover:
>
> * How to write your check plugin so that it works with Flake8 2.x and 3.x
> [...]

**Comment by twolfson** [comment]
Flake8==3 is still in beta and seems to be shifting around their API. We aren't supporting Flake8==3 until it gets out of beta. Please see existing issues #30 and #38 for reference

**Comment by playpauseandstop** [comment]
Actually it is already released, https://pypi.python.org/pypi/flake8/3.0.0

**Comment by twolfson** [comment]
Oh well that was quick. I don't have time to do a full patch at the moment but I will get us to working sans `stdin`

**Comment by twolfson** [comment]
After a small attempt, past assumptions were proven wrong and we are back to square 1. However, this issue was a duplicate of #30 so please refer to #30 as the main thread.

**Comment by twolfson** [comment]
Sorry, I meant issue #29
